# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-09 02:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('smirk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='system_administrator',
            name='username',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
